### ISSUE TITLE
build failed because of toybox

### ISSUE THREAD

**Issue by studi7o** [sonyxperiadev/device-sony-common#223]
Phone: X Compact
AOSP: 6.0.1

got error:  
``` txt
No rule to make target `out/target/product/kugo/utilities/toybox', needed by `out/target/product/kugo/root/init.real'.
```

I tried to build toybox alone
``` bash
$ mmm external/toybox/
```
failed again

**Comment by jerpelea** [comment]
I suspect that you miss a patch. Please use the build guide!

**Comment by studi7o** [comment]
I followed the guide and applied patches, build succeeded. Thank you.
