### ISSUE TITLE
can't flash the provided  odm image

### ISSUE THREAD

**Issue by Bitti09** [sonyxperiadev/device-sony-common#324]
log (as root):
 fastboot flash oem SW_binaries_for_Xperia_AOSP_O_MR0_4.4_v02_tone.img 
target reported max download size of 268435456 bytes
sending 'oem' (212596 KB)...
OKAY [  9.656s]
writing 'oem'...
FAILED (remote: Command not allowed)
finished. total time: 9.670s

Device: Xperia XZ
shasum from zip   checked

**Comment by jamuir** [comment]
@Bitti09 I hit the same problem.  See here:

https://github.com/sonyxperiadev/device-sony-maple/issues/21

We need to wait until Sony releases a new bootloader.

**Comment by alviteri** [comment]
@jamuir latest yoshino stock release allow it to flash oem ......

@Bitti09 tone for now has not this ... unsparse it via simg2img and then flash with dd

**Comment by Bitti09** [comment]
@alviteri  already did it and enjoying oreo :smiley:

**Comment by jamuir** [comment]
Thanks @alviteri .

The problem for me was that EMMA only offered an older device image, which did not include the updated bootloader.  Alin has been trying to fix that (see the issue I linked to).

I realized myself that I could flash the oem partition using `dd` (as you mentioned).  So I did that and now I have a usable image :-)

**Comment by jerpelea** [comment]
please use https://github.com/sonyxperiadev/bug_tracker for future issues
