### ISSUE TITLE
Impossible to rebuild ODM image correctly

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/device-sony-common#336]
I try to regenerate ODM image.

So firstly, I extract filesystem from official Sony ODM image.
`unzip -X -b SW_binaries_for_Xperia_AOSP-N_MR1_4.4_v03-yoshino.zip`
`simg2img SW_binaries_for_Xperia_AOSP-N_MR1_4.4_v03-yoshino.img SW_binaries_for_Xperia_AOSP-N_MR1_4.4_v03-yoshino.raw.img`
`mkdir -p /tmp/odm`
`sudo mount -t ext4 -o loop SW_binaries_for_Xperia_AOSP-N_MR1_4.4_v03-yoshino.raw.img /tmp/odm`
`mkdir -p $(ANDROID_PRODUCT_OUT)/odm`
`cp -rf /tmp/odm/* $(ANDROID_PRODUCT_OUT)/odm/.`

At this point, the file access rights are good for files on "bin" directory (0755). 

But, when I execute "make custom_images", the new ODM image looses file access rights for files on "bin" directory (0644 instead of 0755).

Please tell me how should I fix it.

**Comment by jerpelea** [comment]
The build does not need blobs to compile the Android images
You are not supposed to alter the provided binaries

**Comment by jerpelea** [comment]
please use https://github.com/sonyxperiadev/bug_tracker for future issues
