### ISSUE TITLE
not sure if it is conflict with lineage's own recovery

### ISSUE THREAD

**Issue by qinyj12** [sonyxperiadev/device-sony-common#431]
Excuse me.
 When I'm building lineage 15.1 for Xperia X Compact with Sony AOSP Team's codes, I met a troule.
As I know, lineage 15.1 is using TWRP as its own recovery. But AOSP for Sony is using another recovery. 
When I am building lineage 15.1, these two different recoveries may be conflict and I don't know how to switch off one of them.
Sorry for disturbing.

**Comment by jerpelea** [comment]
unfortunately we can't support custom ROMs because each one is different.
i would suggest to look for build flags in your 15.1 to stop the build of one recovery

**Comment by jerpelea** [comment]
unfortunately we can't support custom ROMs because each one is different.
i would suggest to look for build flags in your 15.1 to stop the build of one recovery

**Comment by qinyj12** [comment]
Cool! Thanks for your reply. Thanks for your team's work.:wink:
