### ISSUE TITLE
Proprietary for Sony Xperia XA F3116

### ISSUE THREAD

**Issue by tranchikha** [sonyxperiadev/device-sony-common#651]
Hello Sony developers,

I had known that you did NOT support for F3116 device. However, could you please provide a prebuilt binaries for graphics of SONY XA (F3116). I would like to create my own project to upgrade my devices to Android P

Thank for reading!

Regards.,
Kha Tran

**Comment by sraase** [comment]
The Sony Xperia XA device uses a completely different platform, based on a Mediatek chipset. We can't provide prebuilt binaries for these.
