### ISSUE TITLE
Xperia 10 II (XQ-AU52) simlock going to be an issue?

### ISSUE THREAD

**Issue by henning-schild** [sonyxperiadev/device-sony-common#875]
I plan to unlock and reflash a XQ-AU52, flash first with emma and the latest android, later move on to sailfish x. The device is offered on ebay saying it has a "Netlock". Is such a lock a pure software thing i can get rid of, or i will get rid of with the bootloader unlock? Or could it be something that will prevent me using that device?

**Comment by jerpelea** [comment]
Unfortunately we can not help you with the Netlock issue 
Please contact the seller or the carrier for Net unlock
